# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Acceptance Tests
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
    paths:
      - '.github/workflows/acceptance-tests.yml'
      - 'tests/**'
      - '**.css'
      - '**.js'
      - '**.php'
      - 'codeception.dist.yml'
      - 'composer.json'
      - 'docker-compose.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/acceptance-tests.yml'
      - 'tests/**'
      - '**.css'
      - '**.js'
      - '**.php'
      - 'codeception.dist.yml'
      - 'composer.json'
      - 'docker-compose.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: WP ${{ matrix.wp }} / PHP ${{ matrix.php }}
    strategy:
      # See the following for PHP compatibility of WordPress versions:
      # https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
      matrix:
        wp:
          # Latest three stable:
          - '6.7-RC1'
          - '6.6'
          - '6.5'
        php:
          - '8.3'
          - '7.4'
        include:
          # Latest stable on PHP 8.3:
          - wp: '6.7-RC1'
            php: '8.4'
          # Oldest supported on PHP 7.4:
          - wp: '5.8'
            php: '7.4'
      fail-fast: false
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-acceptance-tests.yml@trunk
    with:
      node: false
      php: ${{ matrix.php }}
      wp: ${{ matrix.wp }}
