# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Build
on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build
    permissions:
      contents: write
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-build.yml@trunk
    with:
      node: false
      tag: ${{ github.event_name != 'workflow_dispatch' }}
      vendor: true
