# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Coding Standards
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
    paths:
      - '.github/workflows/coding-standards.yml'
      - '**.css'
      - '**.js'
      - '**.php'
      - 'composer.json'
      - 'phpcs.xml.dist'
      - 'phpstan.neon.dist'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/coding-standards.yml'
      - '**.css'
      - '**.js'
      - '**.php'
      - 'composer.json'
      - 'phpcs.xml.dist'
      - 'phpstan.neon.dist'
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: ${{ matrix.label }}
    permissions:
      contents: read
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-coding-standards.yml@157f88f06869cd738b9a0dc4d4ba6b422dba8a1a
    strategy:
      matrix:
        label:
          - 'PHP'
        php:
          - '8.3'
          - '7.4'
      fail-fast: false
    with:
      php: ${{ matrix.php }}
