# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Coding Standards
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
    paths:
      - '.github/workflows/coding-standards.yml'
      - '**.css'
      - '**.js'
      - '**.php'
      - 'composer.json'
      - 'phpcs.xml.dist'
      - 'phpcs56.yml'
      - 'phpstan.neon.dist'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/coding-standards.yml'
      - '**.css'
      - '**.js'
      - '**.php'
      - 'composer.json'
      - 'phpcs.xml.dist'
      - 'phpcs56.yml'
      - 'phpstan.neon.dist'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: PHP
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-coding-standards.yml@test-naming
    strategy:
      matrix:
        php:
          - '8.3'
          - '7.4'
      fail-fast: false
    with:
      php: ${{ matrix.php }}
